name: Bootgly (test)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          ini-file: 'development'
          extensions: mbstring, pcntl
      -
        name: Run Bootgly Test command
        run: php bootgly test --bootgly