name: Bootgly (test)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          ini-file: 'development'
          ini-values: disable_functions=""
          extensions: mbstring, pcntl
      -
        name: Run Bootgly Test command
        run: |
          php bootgly
          php bootgly test --bootgly