name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push HTTP Server CLI image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./@/__docker__/http-server-cli.dockerfile
          push: true
          tags: |
            bootgly/http-server-cli:latest
            ghcr.io/bootgly/http-server-cli:latest
      -
        name: Build and push TCP Server CLI image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./@/__docker__/tcp-server-cli.dockerfile
          push: true
          tags: |
            bootgly/tcp-server-cli:latest
            ghcr.io/bootgly/tcp-server-cli:latest
      -
        name: Build and push TCP Client CLI image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./@/__docker__/tcp-client-cli.dockerfile
          push: true
          tags: |
            bootgly/tcp-client-cli:latest
            ghcr.io/bootgly/tcp-client-cli:latest