name: Bootgly Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Run Bootgly Test command
        run: php bootgly test